name: Build

on: [push]

env:
  BUILD_CACHE: /home/runner/.docker/buildkit
  DOCKER_BUILDKIT: "1"

jobs:
  linux-amd64:
    name: linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_CACHE }}
          key: ${{ hashFiles('Dockerfile') }}
      - run: make PLATFORM=linux/amd64
      - uses: actions/upload-artifact@v2
        with:
          name: go-git-staged_linux-arm64
          path: bin/go-git-staged
          if-no-files-found: error

  darwin-arm64:
    name: darwin/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_CACHE }}
          key: ${{ hashFiles('Dockerfile') }}
      - run: make PLATFORM=darwin/arm64
      - uses: actions/upload-artifact@v2
        with:
          name: go-git-staged_darwin-arm64
          path: bin/go-git-staged
          if-no-files-found: error

  darwin-amd64:
    name: darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_CACHE }}
          key: ${{ hashFiles('Dockerfile') }}
      - run: make PLATFORM=darwin/amd64
      - uses: actions/upload-artifact@v2
        with:
          name: go-git-staged_darwin-amd64
          path: bin/go-git-staged
          if-no-files-found: error

  windows-amd64:
    name: windows/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_CACHE }}
          key: ${{ hashFiles('Dockerfile') }}
      - run: make PLATFORM=windows/amd64
      - uses: actions/upload-artifact@v2
        with:
          name: go-git-staged_windows-amd64
          path: bin/go-git-staged.exe
          if-no-files-found: error
